### ISSUE TITLE
报名参与开发

### ISSUE THREAD

**Issue by Jancd** [guanggu-coder/ggcoder-server#1]
偏后端，go

**Comment by chai2010** [comment]
感谢关注

目前几个目标：

1. 支持module（紧急，能编译的话好能用起来）
2. go test不能失败，就是pkg要独立（这个慢慢来）
3. 拆分中间件，能独立出来一些，向caddy插件方向走

我先加你为成员吧

**Comment by chai2010** [comment]
先加个微信吧，我的 chaishushan-weixin

@Jancd
